create table T_CUSTOMER (
	"CUSTOMER_ID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"NAME" VARCHAR(20) NOT NULL,
	"PHONE" VARCHAR(10)
);

create table T_MASTER (
	"MASTER_ID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"NAME" VARCHAR(20) NOT NULL,
	"ADDRESS" VARCHAR(10)
);

create table T_ORDER (
	"ORDER_ID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"CUSTOMER_ID" INTEGER,
	"MASTER_ID" INTEGER,
	"LOCATION" VARCHAR(20)
);
alter table t_order add foreign key (CUSTOMER_ID) REFERENCES  T_CUSTOMER(customer_id);
alter table t_order add foreign key (MASTER_ID) REFERENCES  T_MASTER(master_id);


insert into T_customer(customer_id , name, phone) values(1, 'john fang', '0936525595');
insert into T_customer(customer_id , name, phone) values(2, 'henry', '0928264905');
insert into t_master(master_id, name, address) values(1, 'ken', 'taipei');
insert into t_order(order_id, customer_id, master_id, location) values(1, 2,1, 'japen');

